-- Tabel referensi negara (m_country) + seed 234 negara dari file query_result.
CREATE TABLE IF NOT EXISTS m_country (
    id            uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    country_name  text NOT NULL,
    country_code  text NOT NULL,
    phone_code    text,
    is_active     boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    created_by    uuid REFERENCES m_internal_user(id) ON DELETE SET NULL,
    modified_at   timestamptz NOT NULL DEFAULT now(),
    modified_by   uuid REFERENCES m_internal_user(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_country_code_lower ON m_country (lower(country_code));
DROP TRIGGER IF EXISTS update_m_country_modified_at ON m_country;
CREATE TRIGGER update_m_country_modified_at BEFORE UPDATE ON m_country FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();

INSERT INTO m_country (country_name, country_code, phone_code) VALUES
  ('AFGHANISTAN', 'AF', '93'),
  ('ALBANIA', 'AL', '355'),
  ('ALGERIA', 'DZ', '213'),
  ('AMERICAN SAMOA', 'AS', '1'),
  ('ANDORRA', 'AD', '376'),
  ('ANGOLA', 'AO', '244'),
  ('ANGUILLA', 'AI', '1'),
  ('ANTIGUA', 'AG', '1'),
  ('ARGENTINA', 'AR', '54'),
  ('ARMENIA', 'AM', '374'),
  ('ARUBA', 'AW', '297'),
  ('AUSTRALIA', 'AU', '61'),
  ('AUSTRIA', 'AT', '43'),
  ('AZERBAIJAN', 'AZ', '994'),
  ('BAHAMAS', 'BS', '1'),
  ('BAHRAIN', 'BH', '973'),
  ('BANGLADESH', 'BD', '880'),
  ('BARBADOS', 'BB', '1'),
  ('BELARUS', 'BY', '375'),
  ('BELGIUM', 'BE', '32'),
  ('BELIZE', 'BZ', '501'),
  ('BENIN', 'BJ', '229'),
  ('BERMUDA', 'BM', '1'),
  ('BHUTAN', 'BT', '975'),
  ('BOLIVIA', 'BO', '591'),
  ('BONAIRE', 'XB', '599'),
  ('BOSNIA AND HERZEGOVINA', 'BA', '387'),
  ('BOTSWANA', 'BW', '267'),
  ('BRAZIL', 'BR', '55'),
  ('BRUNEI', 'BN', '673'),
  ('BULGARIA', 'BG', '359'),
  ('BURKINA FASO', 'BF', '226'),
  ('BURUNDI', 'BI', '257'),
  ('CAMBODIA', 'KH', '855'),
  ('CAMEROON', 'CM', '237'),
  ('CANADA', 'CA', '1'),
  ('CANARY ISLANDS, THE', 'IC', '34'),
  ('CAPE VERDE', 'CV', '238'),
  ('CAYMAN ISLANDS', 'KY', '1'),
  ('CENTRAL AFRICAN REPUBLIC', 'CF', '236'),
  ('CHAD', 'TD', '235'),
  ('CHILE', 'CL', '56'),
  ('CHINA, PEOPLES REPUBLIC', 'CN', '86'),
  ('COLOMBIA', 'CO', '57'),
  ('COMOROS', 'KM', '269'),
  ('CONGO', 'CG', '242'),
  ('CONGO, DPR', 'CD', '243'),
  ('COOK ISLANDS', 'CK', '682'),
  ('COSTA RICA', 'CR', '506'),
  ('COTE D IVOIRE', 'CI', '225'),
  ('CROATIA', 'HR', '385'),
  ('CUBA', 'CU', '53'),
  ('CURACAO', 'XC', '599'),
  ('CYPRUS', 'CY', '357'),
  ('CZECH REP., THE', 'CZ', '420'),
  ('DENMARK', 'DK', '45'),
  ('DJIBOUTI', 'DJ', '253'),
  ('DOMINICAN REPUBLIC', 'DO', '1'),
  ('ECUADOR', 'EC', '593'),
  ('EGYPT', 'EG', '20'),
  ('EL SALVADOR', 'SV', '503'),
  ('ERITREA', 'ER', '291'),
  ('ESTONIA', 'EE', '372'),
  ('ESWATINI', 'SZ', '268'),
  ('ETHIOPIA', 'ET', '251'),
  ('FALKLAND ISLANDS', 'FK', '500'),
  ('FAROE ISLANDS', 'FO', '298'),
  ('FIJI', 'FJ', '679'),
  ('FINLAND', 'FI', '358'),
  ('FRANCE', 'FR', '33'),
  ('FRENCH GUYANA', 'GF', '594'),
  ('GABON', 'GA', '241'),
  ('GAMBIA', 'GM', '220'),
  ('GEORGIA', 'GE', '995'),
  ('GERMANY', 'DE', '49'),
  ('GHANA', 'GH', '233'),
  ('GIBRALTAR', 'GI', '350'),
  ('GREECE', 'GR', '30'),
  ('GREENLAND', 'GL', '299'),
  ('GRENADA', 'GD', '1'),
  ('GUADELOUPE', 'GP', '590'),
  ('GUAM', 'GU', '1'),
  ('GUATEMALA', 'GT', '502'),
  ('GUERNSEY', 'GG', '44'),
  ('GUINEA-BISSAU', 'GW', '245'),
  ('GUINEA-EQUATORIAL', 'GQ', '240'),
  ('GUINEA REP.', 'GN', '224'),
  ('GUYANA', 'GY', '592'),
  ('HAITI', 'HT', '509'),
  ('HONDURAS', 'HN', '504'),
  ('HONG KONG SAR CHINA', 'HK', '852'),
  ('HUNGARY', 'HU', '36'),
  ('ICELAND', 'IS', '354'),
  ('INDIA', 'IN', '91'),
  ('INDONESIA', 'ID', '62'),
  ('IRAN (ISLAMIC REPUBLIC OF)', 'IR', '98'),
  ('IRAQ', 'IQ', '964'),
  ('IRELAND, REP. OF', 'IE', '353'),
  ('ISRAEL', 'IL', '972'),
  ('ITALY', 'IT', '39'),
  ('JAMAICA', 'JM', '1'),
  ('JAPAN', 'JP', '81'),
  ('JERSEY', 'JE', '44'),
  ('JORDAN', 'JO', '962'),
  ('KAZAKHSTAN', 'KZ', '7'),
  ('KENYA', 'KE', '254'),
  ('KIRIBATI', 'KI', '686'),
  ('KOREA,  D.P.R OF', 'KP', '850'),
  ('KOREA, REP. OF', 'KR', '82'),
  ('KOSOVO', 'KV', '383'),
  ('KUWAIT', 'KW', '965'),
  ('KYRGYZSTAN', 'KG', '996'),
  ('LAOS', 'LA', '856'),
  ('LATVIA', 'LV', '371'),
  ('LEBANON', 'LB', '961'),
  ('LESOTHO', 'LS', '266'),
  ('LIBERIA', 'LR', '231'),
  ('LIBYA', 'LY', '218'),
  ('LIECHTENSTEIN', 'LI', '423'),
  ('LITHUANIA', 'LT', '370'),
  ('LUXEMBOURG', 'LU', '352'),
  ('MACAU SAR CHINA', 'MO', '853'),
  ('MADAGASCAR', 'MG', '261'),
  ('MALAWI', 'MW', '265'),
  ('MALAYSIA', 'MY', '60'),
  ('MALDIVES', 'MV', '960'),
  ('MALI', 'ML', '223'),
  ('MALTA', 'MT', '356'),
  ('MARSHALL ISLANDS', 'MH', '692'),
  ('MARTINIQUE', 'MQ', '596'),
  ('MAURITANIA', 'MR', '222'),
  ('MAURITIUS', 'MU', '230'),
  ('MAYOTTE', 'YT', '262'),
  ('MEXICO', 'MX', '52'),
  ('MICRONESIA, FEDERATED STATES OF', 'FM', '691'),
  ('MOLDOVA, REP. OF', 'MD', '373'),
  ('MONACO', 'MC', '377'),
  ('MONGOLIA', 'MN', '976'),
  ('MONTENEGRO, REP OF', 'ME', '382'),
  ('MONTSERRAT', 'MS', '1'),
  ('MOROCCO', 'MA', '212'),
  ('MOZAMBIQUE', 'MZ', '258'),
  ('MYANMAR', 'MM', '95'),
  ('NAMIBIA', 'NA', '264'),
  ('NAURU, REP. OF', 'NR', '674'),
  ('NEPAL', 'NP', '977'),
  ('NETHERLANDS, THE', 'NL', '31'),
  ('NEVIS', 'XN', '1'),
  ('NEW CALEDONIA', 'NC', '687'),
  ('NEW ZEALAND', 'NZ', '64'),
  ('NICARAGUA', 'NI', '505'),
  ('NIGER', 'NE', '227'),
  ('NIGERIA', 'NG', '234'),
  ('NIUE', 'NU', '683'),
  ('NORTHERN MARIANA ISLANDS', 'MP', '1'),
  ('NORTH MACEDONIA', 'MK', '389'),
  ('NORWAY', 'NO', '47'),
  ('OMAN', 'OM', '968'),
  ('PAKISTAN', 'PK', '92'),
  ('PALAU', 'PW', '680'),
  ('PANAMA', 'PA', '507'),
  ('PAPUA NEW GUINEA', 'PG', '675'),
  ('PARAGUAY', 'PY', '595'),
  ('PERU', 'PE', '51'),
  ('PHILIPPINES, THE', 'PH', '63'),
  ('POLAND', 'PL', '48'),
  ('PORTUGAL', 'PT', '351'),
  ('PUERTO RICO', 'PR', '1'),
  ('QATAR', 'QA', '974'),
  ('REUNION, ISLAND OF', 'RE', '262'),
  ('ROMANIA', 'RO', '40'),
  ('RUSSIAN FEDERATION', 'RU', '7'),
  ('RWANDA', 'RW', '250'),
  ('SAINT HELENA', 'SH', '290'),
  ('SAMOA', 'WS', '685'),
  ('SAN MARINO', 'SM', '378'),
  ('SAO TOME AND PRINCIPE', 'ST', '239'),
  ('SAUDI ARABIA', 'SA', '966'),
  ('SENEGAL', 'SN', '221'),
  ('SERBIA, REP. OF', 'RS', '381'),
  ('SEYCHELLES', 'SC', '248'),
  ('SIERRA LEONE', 'SL', '232'),
  ('SINGAPORE', 'SG', '65'),
  ('SLOVAKIA', 'SK', '421'),
  ('SLOVENIA', 'SI', '386'),
  ('SOLOMON ISLANDS', 'SB', '677'),
  ('SOMALIA', 'SO', '252'),
  ('SOMALILAND, REP OF', 'XS', '252'),
  ('SOUTH AFRICA', 'ZA', '27'),
  ('SOUTH SUDAN', 'SS', '211'),
  ('SPAIN', 'ES', '34'),
  ('SRI LANKA', 'LK', '94'),
  ('ST. BARTHELEMY', 'XY', '590'),
  ('ST. EUSTATIUS', 'XE', '599'),
  ('ST. KITTS', 'KN', '1'),
  ('ST. LUCIA', 'LC', '1'),
  ('ST. MAARTEN', 'XM', '1'),
  ('ST. VINCENT', 'VC', '1'),
  ('SUDAN', 'SD', '249'),
  ('SURINAME', 'SR', '597'),
  ('SWEDEN', 'SE', '46'),
  ('SWITZERLAND', 'CH', '41'),
  ('SYRIA', 'SY', '963'),
  ('TAHITI', 'PF', '689'),
  ('TAIWAN', 'TW', '886'),
  ('TAJIKISTAN', 'TJ', '992'),
  ('TANZANIA', 'TZ', '255'),
  ('THAILAND', 'TH', '66'),
  ('TIMOR LESTE', 'TL', '670'),
  ('TOGO', 'TG', '228'),
  ('TONGA', 'TO', '676'),
  ('TRINIDAD AND TOBAGO', 'TT', '1'),
  ('TUNISIA', 'TN', '216'),
  ('TURKEY', 'TR', '90'),
  ('TURKMENISTAN', 'TM', '993'),
  ('TURKS & CAICOS', 'TC', '1'),
  ('TUVALU', 'TV', '688'),
  ('UGANDA', 'UG', '256'),
  ('UKRAINE', 'UA', '380'),
  ('UNITED ARAB EMIRATES', 'AE', '971'),
  ('UNITED KINGDOM', 'GB', '44'),
  ('UNITED STATES OF AMERICA', 'US', '1'),
  ('URUGUAY', 'UY', '598'),
  ('UZBEKISTAN', 'UZ', '998'),
  ('VANUATU', 'VU', '678'),
  ('VATICAN CITY', 'VA', '379'),
  ('VENEZUELA', 'VE', '58'),
  ('VIETNAM', 'VN', '84'),
  ('VIRGIN ISLANDS-BRITISH', 'VG', '1'),
  ('VIRGIN ISLANDS (US)', 'VI', '1'),
  ('YEMEN, REP. OF', 'YE', '967'),
  ('ZAMBIA', 'ZM', '260'),
  ('ZIMBABWE', 'ZW', '263')
ON CONFLICT (lower(country_code)) DO NOTHING;
